### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by NoFaceKaonashi** [zizzfizzix/tracking-for-divi#1]
I can't install, says the main plugin file does not exist, tbh I can't find it either, you said this is just a download and its ready to upload the zip and activate? Ty

**Comment by zizzfizzix** [comment]
Hi, did you download the zip from https://github.com/zizzfizzix/tracking-for-divi/releases/download/v0.2.0/tracking-for-divi.zip?
This would potentially be an issue if you just downloaded the source code from this repository as it requires to be built first.
